version: "1"
services:
  vesta:
    image: kijamve/vestacp
    container_name: vestacp
    cap_add: ['NET_RAW', 'NET_ADMIN']
    hostname: ds1.cuado.co
    volumes:
      - "/opt/vestacp/backup:/backup"
      - "/opt/vestacp/vesta:/vesta"
      - "/opt/vestacp/home:/home"
    ports:
      - "3322:22"
      - "80:80"
      - "443:443"
      - "8083:8083"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    sysctls:
      net.core.somaxconn: '511'
    labels:
      - "Vesta Control Panel"
    restart: always